FROM resin/%%RESIN_MACHINE_NAME%%-python
ENV INITSYSTEM on

RUN apt-get update && apt-get install -yq --no-install-recommends \
    python-pandas && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install Flask speedtest-cli plotly pandas

COPY src/ /usr/src/app
COPY service/ /etc/systemd/system
RUN mkdir -p /usr/src/app/mnt

CMD ["bash", "/usr/src/app/start.sh"]

# env var
# torrents
# server
# relays
